---
# Playbook zur Konfiguration der managed-vms

- hosts: managed-vms
  gather_facts: False
  remote_user: root
  roles:
#    - { role: prepare_guest, tags: "prepare_guest"}
    - { role: vm-network, tags: "vm-network"}
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: mailcow, tags: "mailcow", when: "'mailcow' in hostvars[inventory_hostname]"}
    - { role: graphite, tags: "graphite", when: "'graphite' in hostvars[inventory_hostname]"}
    - { role: graphite_nginx, tags: "graphite_nginx", when: "'graphite' in hostvars[inventory_hostname]"}
