---

- name: install ethtool if required
  apt:
    pkg: "ethtool"
    update_cache: yes
    state: installed
  when: 'multiqueue' in vm_config

- name: configure /etc/network/interfaces/
  template: src="interfaces.j2" dest="/etc/network/interfaces"
  notify:
    - restart networking

- name: Execute all triggered handlers
  meta: flush_handlers