---
- name: destroy guest
  virt:
    command: destroy
    name: "{{inventory_hostname | replace(\"-\",\"_\")}}"
  delegate_facts: True
  delegate_to: "{{hypervisor_inventory_hostname}}"
  failed_when: False

- name: undefine guest
  virt:
    command: undefine
    name: "{{inventory_hostname | replace(\"-\",\"_\")}}"
  delegate_facts: True
  delegate_to: "{{hypervisor_inventory_hostname}}"
  failed_when: False

- name: define guest
  virt:
    command: define
    name: "{{inventory_hostname | replace(\"-\",\"_\")}}"
    xml: "{{the_xml.content | b64decode}}"
  delegate_facts: True
  delegate_to: "{{hypervisor_inventory_hostname}}"

- name: start guest
  virt:
    command: start
    name: "{{inventory_hostname | replace(\"-\",\"_\")}}"
  delegate_facts: True
  delegate_to: "{{hypervisor_inventory_hostname}}"
