---

- include_vars: passwords.yml

- name: install required packages for this role
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 900
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-passlib
    - rsync
    - python-pip
 
- name: add key for docker repo
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D


- name: add repo for docker
  apt_repository: repo='deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }} main' state=present

- name: install docker
  apt:
    pkg: "docker-engine"
    update_cache: yes
    cache_valid_time: 900
    state: installed

- name: install docker-py for ansible management of docker
  pip: 
    name: "docker-py"
    state: present

- name: Start and enable docker
  service: name=docker state=started enabled=yes

- name: create folder for docker config files
  file: path="/usr/src/graphite" state=directory mode=0755

- name: create storage-schemas.conf
  template: src=storage-schemas.conf.j2 dest=/usr/src/graphite/storage-schemas.conf

- name: create .htpasswd
  htpasswd: path=/usr/src/graphite/.htpasswd name='{{graphite.auth.name}}' password='{{graphite.auth.pass}}' crypt_scheme=md5_crypt
  when: "'auth' in graphite"

# create data folders '

- name: create folder graphite data
  file: path=/usr/src/graphite/storage state=directory mode=0755

# configure ramdisk

- name: create persitent folder graphite data
  file: path=/usr/src/graphite/storage/whisper_persistent state=directory mode=0755

- name: create tmp folder graphite data
  file: path=/usr/src/graphite/storage/whisper_volatile state=directory mode=0755

- name: Create link to volatile (tmpfs) path
  file: src=/usr/src/graphite/storage/whisper_volatile dest=/usr/src/graphite/storage/whisper state=link

- name: set swappiness to 0
  sysctl: name=vm.swappiness value=0 state=present

- name: Ramdisk in fstab eintragen
  mount: name=/usr/src/graphite/storage/whisper_volatile src=tmpfs fstype=tmpfs opts='defaults,size={{graphite.ramdisk_size}}' state=mounted

- name: tmpfs start script for graphite
  template: src=openramdisk.j2 dest=/usr/src/graphite/openramdisk mode="a+x"

- name: tmpfs stop script for graphite
  template: src=closeramdisk.j2 dest=/usr/src/graphite/closeramdisk mode="a+x"

- name: tmpfs systemd service for graphite
  template: src=graphite-tmpfs.service.j2 dest=/lib/systemd/system/graphite-tmpfs.service

- name: enable graphite-tmpfs service
  service: name=graphite-tmpfs enabled=yes state=started

- name: Create cron for backing up data every 30 minutes
  cron: name="tmpfs backup" minute="*/30" job="rsync --archive /usr/src/graphite/storage/whisper_volatile/ /usr/src/graphite/storage/whisper_persistent/"

# graphite docker: https://hub.docker.com/r/sitespeedio/graphite/

- name: Configure graphite container
  docker:
    name: graphite
    image: sitespeedio/graphite
    state: reloaded
    restart_policy: always
    pull: missing
    expose:
    - 2003
    - 80
    ports:
    - "8000:80"
    - "2003:2003"
    volumes:
    - "/usr/src/graphite/.htpasswd:/etc/nginx/.htpasswd"
    - "/usr/src/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf"
    - "/usr/src/graphite/storage/whisper:/opt/graphite/storage/whisper"
