#using shell instead of ansible module, because ansible isn't perfect in handling with systemd atm
---
- name: restart networking
  shell: systemctl restart networking

- name: update grub
  shell: update-grub

- name: reboot
  reboot:
    search_paths: ['/lib/molly-guard', '/sbin']
